# Generated by Django 4.1.3 on 2022-11-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vero_social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_vero',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
