# Generated by Django 4.1.3 on 2022-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vero_social', '0002_post_vero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_vero',
            name='tag',
            field=models.CharField(default='vino', max_length=50),
        ),
    ]
