# Generated by Django 4.1.3 on 2022-11-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vero_social', '0003_post_vero_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_vero',
            name='slug_title',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_vero',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
