# Generated by Django 4.1.3 on 2022-12-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vero_social', '0004_post_vero_slug_title_alter_post_vero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag_piaciuti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
    ]
