# Generated by Django 4.1.3 on 2022-12-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vero_social', '0005_tag_piaciuti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_vero',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
