# Generated by Django 4.1.3 on 2022-12-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vero_social', '0006_alter_post_vero_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_vero',
            name='bool_stampato',
            field=models.BooleanField(default=False),
        ),
    ]
